### ISSUE TITLE
Python package

### ISSUE THREAD

**Issue by bloodbare** [tantivy-search/tantivy-py#2]
Could we push to pypi a python package with this bindings? @poljar

**Comment by poljar** [comment]
Sure we can. If @fulmicoton is also fine with it.

**Comment by zhangchunlin** [comment]
As a python user, I think it will be much more convenient if we can use a python package.
Look forward to ~
Thank you.

**Comment by veeshi** [comment]
Bump

**Comment by poljar** [comment]
We have holidays currently and my eyes are a bit non-cooperative. I expect to work on this in the first week of 2020 though. If someone is in a rush before that a PR for the travis setup would be welcome.

**Comment by poljar** [comment]
Releases can be found now on [pypi](https://pypi.org/project/tantivy-py/).

Binary wheels are built for Python 3.7 and 3.8 for Linux/Windows/macOS.
The wheels are built by `maturin` every time a tag is pushed by Travis.

We may want to consider changing the name of the package to just tantivy instead of tantivy-py, this would require changing the name in the `Cargo.toml`. Since this crate will not end up on crates.io this shouldn't be a problem.

If people could check out the RC release on pypi and confirm that they work that would be great.

**Comment by poljar** [comment]
Since nobody commented I decided to change the name of the Python package to `tantivy`. New RC release can be found here https://pypi.org/project/tantivy/.

If someone has any objections speak now, or forever hold your piece. This is going to be released in a week or so as a non-RC version otherwise.

**Comment by fulmicoton** [comment]
I'm all for tantivy!

**Comment by poljar** [comment]
This has been published for a while.
