### ISSUE TITLE
replace setuptools-rust with pyo3-pack

### ISSUE THREAD

**Issue by petr-tik** [tantivy-search/tantivy-py#4]
According to the pyo3-pack README

> This project is meant as a zero configuration replacement for setuptools-rust and milksnake. It supports building wheels for python 3.5+ on windows, linux and mac, can upload them to pypi and has basic pypy support.

Replacing setuptools should make testing, deploying and installing easier

**Comment by poljar** [comment]
I tested pyo3-pack a little bit and it's missing some functionality still, mainly a way to build an sdist: https://github.com/PyO3/setuptools-rust/issues/48#issuecomment-475814329.

We might want to wait for that before we abandon setuptools-rust. I'll provide a patch so that pyo3-pack can be used but leave the setup.py there.

**Comment by poljar** [comment]
pyo3-pack got renamed to [maturin](https://github.com/PyO3/maturin) and it seems that it supports building an sdist now. This can now be properly investigated and prepared for a release.

**Comment by poljar** [comment]
Fixed by c8775c69cca87d1f0e0ead41c172ece7d1e77953.
